import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {RefreshCw} from 'lucide-react';
import {useAuth} from '../../auth/useAuth';
import {getAdminDashboard} from '../../services/adminDashboard.service';
import {formatCurrency} from '../../utils/format';
import './CollectionDashboard.css';
import './AdminDashboard.css';

const actions=[['Importar cartera','/administracion/importar-cartera','portfolio.import'],['Resolver clientes','/administracion/resolucion-clientes','portfolio.import'],['Revisar pagos','/administracion/pagos-reportados','settings.manage'],['Revisar promesas','/administracion/historial-cobranza','history.view',{type:'promise'}],['Ver Pipeline','/cobranza','collection.view'],['Auditoría','/administracion/historial-cobranza','history.view'],['WhatsApp','/administracion/whatsapp','settings.manage'],['Configuración','/administracion/configuracion-cobranza','settings.manage']];
const events={payment_registered:'registró un pago',confirmation_accepted:'confirmó un pago reportado',report_reviewed:'revisó un pago reportado',allocation_created:'asignó un pago',balance_updated:'actualizó un saldo',invoice_settled:'saldó una factura',pipeline_recalculated:'recalculó el Pipeline',pipeline_exited:'retiró un cliente del Pipeline',automatic_collection_blocked:'bloqueó nueva cobranza automática',result_registered:'registró un resultado de gestión',CLIENT_CREATED:'creó un cliente',CLIENT_MARKED_AMBIGUOUS:'marcó un cliente para revisión',sent:'envió WhatsApp',delivered:'registró WhatsApp entregado'};
const connectionLabels={NOT_CONFIGURED:'No configurado',CONFIGURED:'Configurado',CONNECTED:'Conectado',DISCONNECTED:'Desconectado',ERROR:'Error'};
const displayTime=value=>new Intl.DateTimeFormat('es-CO',{timeZone:'America/Bogota',dateStyle:'short',timeStyle:'short'}).format(new Date(value));
function Metric({label,value,money=false}) { return <article><span>{label}</span><strong>{value==null?'No disponible':money?formatCurrency(value):value}</strong></article>; }
function Panel({title,section,onRetry,children}) {
  return <section className="dashboard-panel" aria-label={title}><h3>{title}</h3>{section?.status==='ok'?children:section?.status==='error'?<div role="alert"><p>Error al cargar {title.toLowerCase()}</p><button className="cartera-reset" onClick={onRetry}>Reintentar</button></div>:<p role="status">Cargando…</p>}</section>;
}
function CustomerTable({rows=[],priority=false,referenceDate}) {
  return rows.length?<div className="admin-table-scroll"><table><thead><tr><th>Cliente / NIT</th><th>Saldo</th><th>Etapa</th><th>{priority?'Prioridad':'Cobrador'}</th><th>Factura principal</th><th>Vencimiento</th><th>Días de mora</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><Link to="/cobranza" state={{customerId:row.id,referenceDate}}>{row.name}</Link><small>{row.nit}</small></td><td>{formatCurrency(row.balance)}</td><td>{row.stage}</td><td>{priority?row.priority??'No disponible':row.collector??'No disponible'}</td><td>{row.invoice||'—'}</td><td>{row.due_date||'—'}</td><td>{row.overdue_days??'—'}</td></tr>)}</tbody></table></div>:<p>Sin clientes con saldo pendiente</p>;
}
export default function AdminDashboard() {
  const {permissions=[]}=useAuth(), authorized=permissions.includes('settings.manage');
  const [period,setPeriod]=useState('today'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[revision,setRevision]=useState(0);
  const [state,setState]=useState({data:null,error:'',key:null});
  const key=JSON.stringify({period,...(period==='custom'?{from,to}:{})}), ready=authorized&&(period!=='custom'||Boolean(from&&to));
  useEffect(()=>{
    if(!ready)return;
    const controller=new AbortController();
    getAdminDashboard(JSON.parse(key),{signal:controller.signal}).then(data=>{if(!controller.signal.aborted)setState({data,error:'',key:`${key}:${revision}`});})
      .catch(error=>{if(!controller.signal.aborted)setState({data:null,error:error.message,key:`${key}:${revision}`});});
    return ()=>controller.abort();
  },[ready,key,revision]);
  if(!authorized)return <section className="collection-dashboard"><p role="alert">No tienes permiso para consultar el Centro Administrativo.</p></section>;
  const current=state.key===`${key}:${revision}`,data=current?state.data:null,loading=ready&&!current;
  const refresh=()=>setRevision(value=>value+1), section=name=>data?.[name], summary=section('summary')?.data;
  const collection=section('collection')?.data,recovery=section('recovery')?.data,resolution=section('resolution')?.data,promises=section('promises')?.data,whatsapp=section('whatsapp')?.data,reports=section('reported_payments')?.data;
  return <section className="collection-dashboard admin-dashboard" aria-busy={loading}>
    <header className="dashboard-header"><div><h2>CENTRO ADMINISTRATIVO</h2><p>MERTEL Importaciones</p><small>Última actualización: {data?displayTime(data.updated_at):'—'} · America/Bogota</small></div><button className="cartera-reset" disabled={loading||!ready} onClick={refresh}><RefreshCw size={16}/>Actualizar</button></header>
    <div className="dashboard-filters"><label>Período de actividad<select value={period} onChange={event=>setPeriod(event.target.value)}><option value="today">Hoy</option><option value="7">Últimos 7 días</option><option value="month">Este mes</option><option value="custom">Personalizado</option></select></label>{period==='custom'&&<><label>Desde<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label></>}
      {data&&<p>Actividad: {data.period.from} — {data.period.to} · Referencia de cartera: {data.period.reference_date}</p>}</div>
    {!ready&&<p>Selecciona las fechas del período.</p>}{loading&&<div className="admin-skeleton" role="status">Cargando Centro Administrativo…</div>}{current&&state.error&&<div role="alert">{state.error}<button onClick={refresh}>Reintentar</button></div>}
    <h3>Estado actual</h3>
    <Panel title="Cartera y distribución del Pipeline" section={section('summary')} onRetry={refresh}><div className="dashboard-cards"><Metric label="Cartera total" value={summary?.total_balance} money/><Metric label="Clientes en cobranza" value={summary?.customers_in_collection}/></div><div className="dashboard-stages">{summary?.stages.map(stage=><article key={stage.key}><h4>{stage.label}</h4><strong>{formatCurrency(stage.balance)}</strong><span>{stage.customers} clientes · {stage.documents} documentos</span></article>)}</div>{summary?.warnings?.length>0&&<ul className="dashboard-warnings">{summary.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul>}</Panel>
    <div className="admin-grid"><Panel title="Clientes por resolver" section={section('resolution')} onRetry={refresh}>
      <p className={resolution?.pending?'admin-pending':''}>{resolution?.pending?`${resolution.pending} pendientes`:'Sin clientes pendientes de resolución'}</p>
      {resolution?.pending>0&&<p>Hay clientes pendientes de resolución. El Pipeline puede permanecer limitado hasta resolverlos.</p>}
      <dl className="admin-counts">{[['Pendientes',resolution?.pending],['Encontrados',resolution?.counts.FOUND],['Nuevos',resolution?.counts.NEW],['Ambiguos',resolution?.counts.AMBIGUOUS],['Inválidos',resolution?.counts.INVALID],['Resueltos',(resolution?.counts.RESOLVED||0)+(resolution?.counts.PERSISTENT||0)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      {permissions.includes('portfolio.import')&&<Link to="/administracion/resolucion-clientes">Revisar clientes</Link>}</Panel>
      <Panel title="Pagos reportados pendientes" section={section('reported_payments')} onRetry={refresh}><p className={reports?.count?'admin-pending':''}>{reports?.count?`${reports.count} pendientes`:'Sin pagos reportados pendientes'}</p><p>Valor total informado: {reports&&formatCurrency(reports.amount)}</p><Link to="/administracion/pagos-reportados">Revisar pagos</Link></Panel>
      <Panel title="Promesas" section={section('promises')} onRetry={refresh}><div className="dashboard-cards"><Metric label="Activas" value={promises?.active}/><Metric label="Vencidas" value={promises?.overdue}/><Metric label="Próximas a vencer (5 días)" value={promises?.upcoming}/></div>{Number(promises?.overdue)===0&&<p>Sin promesas vencidas</p>}{permissions.includes('history.view')&&<Link to="/administracion/historial-cobranza" state={{type:'promise'}}>Revisar promesas</Link>}</Panel>
      <Panel title="WhatsApp" section={section('whatsapp')} onRetry={refresh}><p>{connectionLabels[whatsapp?.connection_status]||'No disponible'}</p>{whatsapp?.provider==='MOCK'&&<strong>MOCK — conexión simulada</strong>}<p>{whatsapp?.pending} mensajes pendientes actuales · {whatsapp?.failed_current} fallidos actuales</p><p>Mensajes creados en el período, por estado actual:</p><dl className="admin-counts">{[['Enviados',whatsapp?.sent],['Entregados',whatsapp?.delivered],['Leídos',whatsapp?.read_count],['Fallidos',whatsapp?.failed]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{Number(whatsapp?.failed)===0&&<p>Sin mensajes fallidos en el período</p>}<Link to="/administracion/whatsapp">Ir a WhatsApp</Link></Panel></div>
    <h3>Actividad del período</h3>
    <Panel title="Actividad de cobranza" section={section('collection')} onRetry={refresh}><div className="dashboard-cards"><Metric label="Clientes gestionados" value={collection?.managed_customers}/><Metric label="Gestiones realizadas" value={collection?.actions_count}/><Metric label="Contactos exitosos (CONTACTED)" value={collection?.contacts}/><Metric label="Clientes sin respuesta (NO_RESPONSE)" value={collection?.no_response}/></div></Panel>
    <Panel title="Recuperación" section={section('recovery')} onRetry={refresh}><p>Pagos confirmados registrados en el período; sin atribución comercial a gestiones.</p><div className="dashboard-cards"><Metric label="Pagos registrados" value={recovery?.payments_count}/><Metric label="Valor de payments" value={recovery?.payments_amount} money/><Metric label="Monto de allocations" value={recovery?.allocations_amount} money/><Metric label="Facturas saldadas (eventos auditados)" value={recovery?.settled_invoices}/><Metric label="Pagos reportados confirmados" value={recovery?.confirmed_reports}/><Metric label="Promesas cumplidas" value={promises?.fulfilled_period}/><Metric label="Recuperación atribuida a gestión"/></div><p>Resultados de gestión: {collection?`${collection.partial_payments} pagos parciales · ${collection.full_payments} pagos completos`:'No disponible'}. No representa todos los payments históricos.</p></Panel>
    <Panel title="Actividad reciente" section={section('recent_activity')} onRetry={refresh}>{section('recent_activity')?.data.length?<ol className="admin-activity">{section('recent_activity').data.map(event=><li key={event.id}><time>{displayTime(event.occurred_at)}</time><span>{event.actor} · {events[event.action]||(event.action==='create'&&event.entity_type==='payment_promise'?'registró una promesa':event.action)}</span>{event.customer_name&&<span>{event.customer_name}</span>}{event.invoice_number&&<span>{event.invoice_number}</span>}{event.amount&&<strong>{formatCurrency(event.amount)}</strong>}{event.customer_id&&permissions.includes('collection.view')&&<Link to="/cobranza" state={{customerId:event.customer_id,referenceDate:data?.period.reference_date}}>Ver cliente</Link>}{permissions.includes('history.view')&&<Link to="/administracion/historial-cobranza" state={{type:event.entity_type==='payment_promise'?'promise':'all',q:event.customer_name||''}}>Ver auditoría</Link>}</li>)}</ol>:<p>Sin actividad reciente en el período</p>}</Panel>
    <Panel title="Mayor cartera pendiente" section={section('top_customers')} onRetry={refresh}><CustomerTable rows={section('top_customers')?.data} referenceDate={data?.period.reference_date}/></Panel>
    <Panel title="Clientes de mayor prioridad" section={section('priority_customers')} onRetry={refresh}><CustomerTable rows={section('priority_customers')?.data} priority referenceDate={data?.period.reference_date}/></Panel>
    <section className="dashboard-panel"><h3>Acciones rápidas</h3><nav className="admin-quick" aria-label="Acciones rápidas">{actions.filter(([, ,permission])=>permissions.includes(permission)).map(([label,path,,linkState])=><Link key={label} to={path} state={linkState}>{label}</Link>)}</nav></section>
  </section>;
}
