import { useEffect, useState } from "react";
import { useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { useAuth } from "../../auth/useAuth";
import { analyzeCustomerResolution, decideCustomerResolution, getCustomerResolution } from "../../services/portfolioImport.service";
import { generatePortfolioPipeline } from "../../services/portfolioImport.service";
import { localDateValue } from "../Cobranza/collection.presentation";
import "./CustomerResolution.css";

const statusLabels = { SEARCHING:"Buscando", FOUND:"Encontrado", NEW:"Nuevo", AMBIGUOUS:"Requiere revisión", INVALID:"Inválido", PERSISTENT:"Cliente encontrado", RESOLVED:"Resuelto" };
const fields = [["name","Nombre"],["address","Dirección"],["city","Ciudad"],["phone","Teléfono"],["credit_limit","Cupo"]];

export default function CustomerResolution() {
  const { permissions=[] } = useAuth(); const allowed=permissions.includes("portfolio.import");
  const location=useLocation(); const navigate=useNavigate(); const [params,setParams]=useSearchParams();
  const batchId=params.get("batch_id"); const [file,setFile]=useState(location.state?.file || null);
  const [data,setData]=useState(null); const [selectedId,setSelectedId]=useState(null); const [filter,setFilter]=useState(params.get("status") || "ALL"); const [search,setSearch]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [fieldChoices,setFieldChoices]=useState({}); const [reason,setReason]=useState(""); const [manualNit,setManualNit]=useState(""); const [manualName,setManualName]=useState(""); const [candidateId,setCandidateId]=useState(""); const [pendingAction,setPendingAction]=useState(null);
  const [referenceDate,setReferenceDate]=useState(localDateValue);
  const selected=data?.rows.find(row=>row.id===selectedId) || data?.rows[0] || null;
  const counts=data?.counts || {};
  useEffect(()=>{ if(!allowed||!batchId)return undefined; const controller=new AbortController(); getCustomerResolution(batchId,{status:filter,search,signal:controller.signal}).then(result=>{if(!controller.signal.aborted){setData(result);setSelectedId(current=>result.rows.some(row=>row.id===current)?current:result.rows[0]?.id||null);}}).catch(reason=>{if(!controller.signal.aborted)setError(reason.message);});return()=>controller.abort(); },[allowed,batchId,filter,search]);
  async function startResolution(){ if(!file||!batchId)return;setBusy(true);setError("");try{setData(await analyzeCustomerResolution(file,batchId));setNotice("Identidades analizadas y asociadas al lote.");}catch(reason){setError(reason.message);}finally{setBusy(false);} }
  async function openPipeline(){if(!file||!data?.ready_for_pipeline)return;setBusy(true);setError("");try{const result=await generatePortfolioPipeline(file,referenceDate);navigate("/cobranza",{state:{portfolioPipeline:result}});}catch(reason){setError(reason.message);}finally{setBusy(false);}}
  async function decide(decision,extra={}) { if(!selected)return false;setBusy(true);setError("");setNotice("");try{const result=await decideCustomerResolution(selected.id,batchId,{decision,reason:reason.trim()||undefined,...extra});setData(result);setNotice("Decisión guardada y auditada.");setReason("");return true;}catch(reason){setError(reason.message);return false;}finally{setBusy(false);} }
  async function confirmAction(){if(!pendingAction)return;if(await decide(pendingAction.decision,pendingAction.extra))setPendingAction(null);}
  const visibleRows=data?.rows || [];
  if(!allowed)return <section className="customer-resolution"><div role="alert" className="resolution-notice error">No tienes permiso para resolver clientes.</div></section>;
  return <section className="customer-resolution">
    <header><div><h2>Resolución de clientes</h2><p>Confirma la identidad de los clientes del archivo antes de continuar al pipeline.</p></div><button type="button" className="resolution-secondary" onClick={()=>navigate("/administracion/importar-cartera")}>Volver a importaciones</button></header>
    {!batchId&&<div className="resolution-card"><h3>Selecciona una importación</h3><p>Abre “Ver resolución de clientes” desde el resultado del análisis para conservar la referencia del lote.</p></div>}
    {batchId&&<><div className="resolution-card"><div className="resolution-summary">{[["Pendientes",data?.pending??"—"],["Encontrados",counts.PERSISTENT??0],["Nuevos",counts.NEW??0],["Ambiguos",counts.AMBIGUOUS??0],["Inválidos",counts.INVALID??0],["Resueltos",counts.RESOLVED??0]].map(([label,value])=><article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div>
      {(!data||Object.values(counts).every(value=>value===0))&&<><p>Selecciona el mismo XLSX de la importación para buscar clientes y conservar el origen.</p><label className="resolution-file">Archivo XLSX<input type="file" accept=".xlsx" onChange={event=>setFile(event.target.files?.[0]||null)}/></label><button disabled={busy||!file} onClick={startResolution}>{busy?"Analizando…":"Analizar y buscar clientes"}</button></>}
      {data?.ready_for_pipeline&&<><p className="resolution-success">Todos los clientes tienen una asociación persistente. La conciliación y el pipeline pueden continuar.</p><div className="resolution-field"><label>Fecha de referencia<input type="date" value={referenceDate} onChange={event=>setReferenceDate(event.target.value)}/></label><button disabled={busy||!file||!referenceDate} onClick={openPipeline}>Generar pipeline</button></div>{!file&&<><label className="resolution-file">Vuelve a seleccionar el XLSX para abrir pipeline<input type="file" accept=".xlsx" onChange={event=>setFile(event.target.files?.[0]||null)}/></label></>}</>}
      {data?.pending>0&&<p className="resolution-warning">Hay {data.pending} clientes pendientes de resolución. El pipeline permanecerá bloqueado hasta resolverlos.</p>}
      {error&&<div role="alert" className="resolution-notice error">{error}</div>}{notice&&<div role="status" className="resolution-notice">{notice}</div>}
    </div>
    {data&&<div className="resolution-workspace"><section className="resolution-card"><div className="resolution-filters"><label>Estado<select aria-label="Filtrar estado" value={filter} onChange={event=>{setFilter(event.target.value);setParams({batch_id:batchId,status:event.target.value});}}>{[["ALL","Todos"],["SEARCHING","Pendientes de búsqueda"],["FOUND","Encontrados"],["NEW","Nuevos"],["AMBIGUOUS","Ambiguos"],["INVALID","Inválidos"],["RESOLVED","Resueltos"],["PERSISTENT","Persistentes"]].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Buscar NIT, nombre o ID<input aria-label="Buscar cliente" value={search} onChange={event=>setSearch(event.target.value)} /></label></div>
      <div className="resolution-table-wrap"><table><thead><tr><th>Estado</th><th>NIT</th><th>Cliente</th><th>Filas</th><th>Cliente asociado</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.id} role="button" tabIndex={0} aria-selected={row.id===selected?.id} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();event.currentTarget.click();}}} onClick={()=>{setSelectedId(row.id);setFieldChoices({});setManualNit("");setManualName("");setCandidateId("");}}><td><span className={`resolution-badge ${row.status.toLowerCase()}`}>{statusLabels[row.status]}</span></td><td>{row.nit_normalized||"—"}</td><td>{row.source_data.name||"Sin nombre"}</td><td>{row.source_rows.join(", ")}</td><td>{row.customer_id||"Pendiente"}</td></tr>)}{!visibleRows.length&&<tr><td colSpan="5">No hay clientes en este filtro.</td></tr>}</tbody></table></div>
    </section>
    {selected&&<section className="resolution-card resolution-detail"><h3>{statusLabels[selected.status]} · NIT {selected.nit_normalized||"sin NIT"}</h3><div className="resolution-compare"><div><h4>Datos del Excel</h4><dl>{Object.entries(selected.source_data).filter(([key])=>!key.endsWith("_normalized")).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value??"—"}</dd></div>)}</dl></div><div><h4>Clientes existentes con este NIT</h4>{selected.candidates?.length?selected.candidates.map(candidate=><label className="resolution-candidate" key={candidate.id}><input type="radio" name="candidate" checked={candidateId===candidate.id} onChange={()=>setCandidateId(candidate.id)}/><span><strong>{candidate.name}</strong><small>ID {candidate.id} · {candidate.nit} · {candidate.city||"Ciudad no informada"}</small></span></label>):<p>No hay cliente existente con este NIT.</p>}</div></div>
      {selected.differences?.length>0&&<div className="resolution-differences"><h4>Datos diferentes</h4><table><thead><tr><th>Campo</th><th>Actual</th><th>Excel</th></tr></thead><tbody>{selected.differences.map(change=><tr key={change.field}><th>{change.field}</th><td>{change.current}</td><td>{change.source}</td></tr>)}</tbody></table></div>}
      <label>Motivo (opcional)<input value={reason} onChange={event=>setReason(event.target.value)} maxLength={500}/></label>
      {selected.status==="NEW"&&<button disabled={busy} onClick={()=>setPendingAction({decision:"create"})}>Crear cliente</button>}
      {(["AMBIGUOUS","FOUND"].includes(selected.status))&&selected.candidates?.length>0&&<button disabled={busy} onClick={()=>setPendingAction({decision:"confirm_same",extra:{customer_id:candidateId||selected.customer_id||selected.candidates[0].id}})}>Este es el mismo cliente</button>}
      {selected.status==="AMBIGUOUS"&&selected.candidates?.length===0&&<button disabled={busy} onClick={()=>setPendingAction({decision:"create"})}>Crear como cliente nuevo</button>}
      {selected.candidates?.length>0&&["AMBIGUOUS","PERSISTENT","RESOLVED"].includes(selected.status)&&<details><summary>Revisar y actualizar campos</summary>{fields.map(([key,label])=><div className="resolution-field" key={key}><label>{label}<select aria-label={`Decisión ${label}`} value={fieldChoices[key]?.mode||"keep"} onChange={event=>setFieldChoices(current=>({...current,[key]:{...current[key],mode:event.target.value}}))}><option value="keep">Mantener actual</option><option value="source">Usar dato del Excel</option><option value="manual">Editar manualmente</option></select></label>{fieldChoices[key]?.mode==="manual"&&<input aria-label={`Valor manual ${label}`} value={fieldChoices[key].value} onChange={event=>setFieldChoices(current=>({...current,[key]:{...current[key],value:event.target.value}}))}/>}</div>)}<button disabled={busy} onClick={()=>setPendingAction({decision:"update",extra:{customer_id:candidateId||selected.customer_id||selected.candidates[0].id,fields:Object.fromEntries(fields.map(([key])=>[key,fieldChoices[key]?.mode==="manual"?{mode:"manual",value:fieldChoices[key].value}:{mode:fieldChoices[key]?.mode||"keep"}]))}})}>Guardar cambios seleccionados</button></details>}
      {selected.status==="INVALID"&&<details><summary>Corregir datos antes de resolver</summary><label>NIT corregido<input value={manualNit||selected.source_data.nit||""} onChange={event=>setManualNit(event.target.value)}/></label><label>Nombre del cliente<input value={manualName||selected.source_data.name||""} onChange={event=>setManualName(event.target.value)}/></label><button disabled={busy} onClick={()=>setPendingAction({decision:"correct",extra:{corrections:{nit:manualNit||selected.source_data.nit,name:manualName||selected.source_data.name}}})}>Validar NIT y volver a revisar</button></details>}
      {!["PERSISTENT","RESOLVED"].includes(selected.status)&&<button className="resolution-secondary" disabled={busy} onClick={()=>setPendingAction({decision:"review"})}>Marcar para revisión</button>}
      {pendingAction&&<div className="resolution-confirm-backdrop"><section role="dialog" aria-modal="true" aria-label="Confirmar decisión" className="resolution-confirm"><h3>Confirmar decisión</h3><p>{pendingAction.decision==="create"?`Crear el cliente ${selected.source_data.name||"del archivo"} con NIT ${selected.nit_normalized||"corregido"}?`:pendingAction.decision==="update"?"Guardar únicamente los campos seleccionados del cliente?":pendingAction.decision==="confirm_same"?"Asociar este registro al cliente seleccionado?":pendingAction.decision==="correct"?"Guardar la corrección del NIT para volver a revisar el registro?":"Dejar este cliente marcado para revisión?"}</p><div><button type="button" disabled={busy} onClick={confirmAction}>Confirmar</button><button type="button" className="resolution-secondary" onClick={()=>setPendingAction(null)}>Cancelar</button></div></section></div>}
    </section>}</div>}</>}
  </section>;
}
