import {beforeEach,expect,it,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {AuthContext} from '../src/auth/auth.context';
import AdminDashboard from '../src/pages/Administracion/AdminDashboard';
import {getAdminDashboard} from '../src/services/adminDashboard.service';
vi.mock('../src/services/adminDashboard.service',()=>({getAdminDashboard:vi.fn()}));
const ok=data=>({status:'ok',data});
const data={updated_at:'2026-10-07T15:00:00Z',period:{from:'2026-10-07',to:'2026-10-07',reference_date:'2026-10-07'},summary:ok({total_balance:'1000',customers_in_collection:2,stages:[{key:'overdue',label:'En mora',balance:'500',customers:1,documents:1}],warnings:[]}),collection:ok({actions_count:3,managed_customers:2,contacts:1,no_response:1,partial_payments:1,full_payments:0}),recovery:ok({payments_count:2,payments_amount:'100',allocations_amount:'80',settled_invoices:1,confirmed_reports:1}),reported_payments:ok({count:0,amount:'0'}),resolution:ok({pending:0,counts:{FOUND:0,NEW:0,AMBIGUOUS:0,INVALID:0,RESOLVED:0,PERSISTENT:0}}),promises:ok({active:1,overdue:0,upcoming:1,fulfilled_period:1}),whatsapp:ok({provider:'MOCK',connection_status:'CONNECTED',pending:0,sent:1,delivered:0,read_count:0,failed:0}),recent_activity:ok([{id:'1',occurred_at:'2026-10-07T15:00:00Z',actor:'Sistema',action:'pipeline_exited'}]),top_customers:ok([]),priority_customers:ok([])};
function view(permissions=['settings.manage','collection.view','history.view','portfolio.import']){render(<MemoryRouter><AuthContext.Provider value={{permissions}}><AdminDashboard/></AuthContext.Provider></MemoryRouter>);}
beforeEach(()=>{vi.clearAllMocks();getAdminDashboard.mockResolvedValue(data);});
it('admin loads real source cards, empty states, MOCK warning and navigation',async()=>{view();expect(screen.getByText('Cargando Centro Administrativo…')).toHaveTextContent('Cargando');await screen.findByText('MOCK — conexión simulada');expect(screen.getByText('Sin pagos reportados pendientes')).toBeVisible();expect(screen.getByText('Sin promesas vencidas')).toBeVisible();expect(screen.getByText(/Sistema · retiró/)).toBeVisible();expect(screen.getByRole('link',{name:'Ver Pipeline'})).toHaveAttribute('href','/cobranza');expect(screen.getAllByRole('link',{name:'Revisar pagos',exact:true})[0]).toBeDefined();});
it('denies unauthorized users without fetching metrics',()=>{view([]);expect(screen.getByRole('alert')).toHaveTextContent('No tienes permiso');expect(getAdminDashboard).not.toHaveBeenCalled();});
it('period, custom dates and refresh request API instead of changing figures',async()=>{view();await screen.findByText('MOCK — conexión simulada');fireEvent.change(screen.getByLabelText('Período de actividad'),{target:{value:'7'}});await waitFor(()=>expect(getAdminDashboard).toHaveBeenLastCalledWith({period:'7'},expect.anything()));fireEvent.change(screen.getByLabelText('Período de actividad'),{target:{value:'custom'}});fireEvent.change(screen.getByLabelText('Desde'),{target:{value:'2026-10-01'}});fireEvent.change(screen.getByLabelText('Hasta'),{target:{value:'2026-10-07'}});await waitFor(()=>expect(getAdminDashboard).toHaveBeenLastCalledWith({period:'custom',from:'2026-10-01',to:'2026-10-07'},expect.anything()));await screen.findByText('MOCK — conexión simulada');const count=getAdminDashboard.mock.calls.length;fireEvent.click(screen.getByRole('button',{name:'Actualizar'}));await waitFor(()=>expect(getAdminDashboard).toHaveBeenCalledTimes(count+1));});
it('partial error preserves financial sections and offers retry',async()=>{getAdminDashboard.mockResolvedValue({...data,whatsapp:{status:'error'}});view();await screen.findByText('Error al cargar whatsapp');expect(screen.getByText('Cartera total')).toBeVisible();expect(screen.getByText('Valor de payments')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Reintentar'}));await waitFor(()=>expect(getAdminDashboard).toHaveBeenCalledTimes(2));});
it('whole request error does not show zero placeholders',async()=>{getAdminDashboard.mockRejectedValue(new Error('API no disponible'));view();await screen.findByText('API no disponible');expect(screen.queryByText('Cartera total')).not.toBeInTheDocument();});
