import { beforeEach, describe, expect, it, vi } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { AuthContext } from "../src/auth/auth.context";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import CustomerResolution from "../src/pages/Administracion/CustomerResolution";
import { analyzeCustomerResolution, decideCustomerResolution, generatePortfolioPipeline, getCustomerResolution } from "../src/services/portfolioImport.service";

vi.mock("../src/services/portfolioImport.service",()=>({analyzeCustomerResolution:vi.fn(),decideCustomerResolution:vi.fn(),generatePortfolioPipeline:vi.fn(),getCustomerResolution:vi.fn()}));
const rows=[
  {id:"10",status:"AMBIGUOUS",nit_normalized:"8000012690",source_rows:[8],source_data:{nit:"800.001.269-0",nit_normalized:"8000012690",name:"Empresa XLSX",phone:"3001111111",address:"Calle 1",city:"Bogotá",credit_limit:1000},customer_id:"1",current:{nit:"800001269-0",name:"Empresa actual"},candidates:[{id:"1",nit:"800001269-0",name:"Empresa actual",address:"Calle 1",city:"Bogotá",phone:"3002222222",credit_limit:800}],differences:[{field:"name",current:"Empresa actual",source:"Empresa XLSX"}]},
  {id:"11",status:"NEW",nit_normalized:"800009991",source_rows:[9],source_data:{nit:"800009991",name:"Cliente nuevo"},customer_id:null,current:null,candidates:[],differences:[]},
  {id:"12",status:"INVALID",nit_normalized:null,source_rows:[10],source_data:{nit:"",name:"Cliente inválido"},customer_id:null,current:null,candidates:[],differences:[]},
  {id:"13",status:"PERSISTENT",nit_normalized:"8000012700",source_rows:[11],source_data:{nit:"8000012700",name:"Cliente resuelto"},customer_id:"2",current:{name:"Cliente resuelto"},candidates:[{id:"2",nit:"8000012700",name:"Cliente resuelto"}],differences:[]},
];
const payload={batch_id:"77",counts:{SEARCHING:0,FOUND:0,NEW:1,AMBIGUOUS:1,INVALID:1,PERSISTENT:1,RESOLVED:0},pending:3,ready_for_pipeline:false,rows};
function view({permissions=["portfolio.import"],initialData=payload}={}){getCustomerResolution.mockResolvedValue(initialData);return render(<AuthContext.Provider value={{user:{id:"1"},permissions}}><MemoryRouter initialEntries={["/administracion/resolucion-clientes?batch_id=77"]}><Routes><Route path="/administracion/resolucion-clientes" element={<CustomerResolution/>}/><Route path="/cobranza" element={<div>pipeline listo</div>}/><Route path="/administracion/importar-cartera" element={<div>importaciones</div>}/></Routes></MemoryRouter></AuthContext.Provider>);}
beforeEach(()=>{vi.clearAllMocks();getCustomerResolution.mockResolvedValue(payload);analyzeCustomerResolution.mockResolvedValue(payload);decideCustomerResolution.mockResolvedValue(payload);generatePortfolioPipeline.mockResolvedValue({});});

describe("Centro de resolución de clientes MERTEL",()=>{
  it("shows batch counters, pending warning, status badges, source rows and customer IDs",async()=>{view();expect(await screen.findByRole("heading",{name:"Resolución de clientes"})).toBeVisible();expect(screen.getByText(/Hay 3 clientes pendientes de resolución/)).toBeVisible();expect(await screen.findAllByText("Empresa XLSX")).toHaveLength(3);expect(screen.getByText("Cliente asociado")).toBeVisible();});
  it("filters by status and searches the displayed customer table",async()=>{const user=userEvent.setup();view();getCustomerResolution.mockImplementation((id,{status})=>Promise.resolve({...payload,rows:status==="AMBIGUOUS"?[rows[0]]:rows}));await screen.findByText("Cliente nuevo");await user.selectOptions(screen.getByLabelText("Filtrar estado"),"AMBIGUOUS");await waitFor(()=>expect(getCustomerResolution).toHaveBeenLastCalledWith("77",expect.objectContaining({status:"AMBIGUOUS",search:""})));expect(await screen.findAllByText("Empresa XLSX")).toHaveLength(3);expect(screen.queryByText("Cliente nuevo")).not.toBeInTheDocument();});
  it("shows a side-by-side profile comparison and confirms the same customer",async()=>{const user=userEvent.setup();view();await screen.findAllByText("Empresa XLSX");expect(screen.getByText("Clientes existentes con este NIT")).toBeVisible();expect(screen.getByText("Datos diferentes")).toBeVisible();await user.click(screen.getByRole("button",{name:"Este es el mismo cliente"}));await user.click(screen.getByRole("button",{name:"Confirmar",exact:true}));await waitFor(()=>expect(decideCustomerResolution).toHaveBeenCalledWith("10","77",expect.objectContaining({decision:"confirm_same",customer_id:"1"})));});
  it("creates a NEW customer only after explicit confirmation",async()=>{const user=userEvent.setup();view();await user.click(await screen.findByText("Cliente nuevo"));await user.click(screen.getByRole("button",{name:"Crear cliente"}));expect(decideCustomerResolution).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Confirmar",exact:true}));await waitFor(()=>expect(decideCustomerResolution).toHaveBeenCalledWith("11","77",expect.objectContaining({decision:"create"})));});
  it("supports field-by-field keep, source and manual edits with a reason",async()=>{const user=userEvent.setup();view();await screen.findAllByText("Empresa XLSX");await user.click(screen.getByText("Revisar y actualizar campos"));await user.selectOptions(screen.getByLabelText("Decisión Teléfono"),"source");await user.selectOptions(screen.getByLabelText("Decisión Dirección"),"manual");await user.type(screen.getByLabelText("Valor manual Dirección"),"Avenida 2");await user.type(screen.getByLabelText("Motivo (opcional)"),"Validado con el cliente");await user.click(screen.getByRole("button",{name:"Guardar cambios seleccionados"}));await user.click(screen.getByRole("button",{name:"Confirmar",exact:true}));await waitFor(()=>expect(decideCustomerResolution).toHaveBeenCalledWith("10","77",expect.objectContaining({decision:"update",customer_id:"1",reason:"Validado con el cliente",fields:expect.objectContaining({phone:{mode:"source"},address:{mode:"manual",value:"Avenida 2"},city:{mode:"keep"}})})));});
  it("lets an administrator correct an invalid NIT before creating a customer",async()=>{const user=userEvent.setup();view();await user.click(await screen.findByText("Cliente inválido"));await user.click(screen.getByText("Corregir datos antes de resolver"));await user.clear(screen.getByLabelText("NIT corregido"));await user.type(screen.getByLabelText("NIT corregido"),"800001299");await user.click(screen.getByRole("button",{name:"Validar NIT y volver a revisar"}));await user.click(screen.getByRole("button",{name:"Confirmar",exact:true}));await waitFor(()=>expect(decideCustomerResolution).toHaveBeenCalledWith("12","77",expect.objectContaining({decision:"correct",corrections:{nit:"800001299",name:"Cliente inválido"}})));});
  it("keeps pipeline unavailable while unresolved rows remain",async()=>{view();await screen.findByText(/Hay 3 clientes pendientes de resolución/);expect(screen.queryByRole("button",{name:"Generar pipeline"})).not.toBeInTheDocument();expect(generatePortfolioPipeline).not.toHaveBeenCalled();});
  it("offers pipeline after the batch reports all identities persistent",async()=>{view({initialData:{...payload,counts:{...payload.counts,NEW:0,AMBIGUOUS:0,INVALID:0,PERSISTENT:3},pending:0,ready_for_pipeline:true,rows:[rows[3]]}});expect(await screen.findByText(/Todos los clientes tienen una asociación persistente/)).toBeVisible();expect(screen.getByRole("button",{name:"Generar pipeline"})).toBeVisible();});
  it("blocks unauthorized users and reports API errors",async()=>{view({permissions:["collection.view"]});expect(screen.getByRole("alert")).toHaveTextContent("No tienes permiso");getCustomerResolution.mockRejectedValueOnce(new Error("Lote no disponible"));render(<AuthContext.Provider value={{user:{id:"1"},permissions:["portfolio.import"]}}><MemoryRouter initialEntries={["/administracion/resolucion-clientes?batch_id=77"]}><Routes><Route path="/administracion/resolucion-clientes" element={<CustomerResolution/>}/></Routes></MemoryRouter></AuthContext.Provider>);expect(await screen.findByText("Lote no disponible")).toBeVisible();});
});
