import { useCallback, useMemo, useState } from "react";
import { X } from "lucide-react";
import { formatCurrency, formatDate } from "../../utils/format";
import { stageLabel } from "./collection.presentation";
import "../Cartera/Cartera.css";
import "./Cobranza.css";

function DetailValue({ label, children }) { return <div className="cobranza-detail-value"><span>{label}</span><strong>{children || "—"}</strong></div>; }
const amount = value => value == null || value === "" ? "—" : formatCurrency(value);
function StageBadge({ item, catalog }) { const category = catalog.find(row => row.key === item.stage)?.category; const tone = category === "overdue" ? "overdue" : category === "prompt_payment" ? "current" : "due_today"; return <span className={`cartera-status cartera-status-${tone}`}>{stageLabel(item.stage, catalog, item.stage_label)}</span>; }

export default function PortfolioPipelineView({ data }) {
  const [query, setQuery] = useState(""); const [stage, setStage] = useState(""); const [collector, setCollector] = useState("");
  const [seller, setSeller] = useState(""); const [city, setCity] = useState(""); const [zone, setZone] = useState(""); const [sort, setSort] = useState("priority");
  const [selected, setSelected] = useState(null); const [showErrors, setShowErrors] = useState(false);
  const catalog = data.stage_catalog || []; const pipeline = useMemo(() => data.pipeline || [], [data.pipeline]);
  const options = key => [...new Set(pipeline.map(item => item.source_details?.[key]).filter(Boolean))].sort((a, b) => a.localeCompare(b));
  const visible = useMemo(() => {
    const norm = value => String(value ?? "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
    const rows = pipeline.filter(item => (!stage || item.stage === stage) && [item.customer?.name, item.customer?.nit, ...item.documents.map(doc => doc.document_number)].some(value => norm(value).includes(norm(query))) &&
      (!collector || item.source_details?.collector === collector) && (!seller || item.source_details?.seller === seller) && (!city || item.source_details?.city === city) && (!zone || item.source_details?.zone === zone));
    return rows.sort((a, b) => sort === "name" ? String(a.customer?.name || "").localeCompare(String(b.customer?.name || "")) : sort === "due" ? String(a.main_invoice?.invoice?.due_date || "").localeCompare(String(b.main_invoice?.invoice?.due_date || "")) : sort === "balance" ? Number(b.total_balance) - Number(a.total_balance) : b.priority - a.priority);
  }, [pipeline, stage, query, collector, seller, city, zone, sort]);
  const close = useCallback(() => setSelected(null), []);
  return <section className="cartera-page cobranza-page">
    <header className="cartera-header"><div><h1>Pipeline de cartera importada</h1><p>Fuente: archivo de cartera MERTEL · {data.source?.file_name} · Procesado: {formatDate(data.source?.processed_at)} · Referencia: {formatDate(data.source?.reference_date)}</p></div></header>
    <div className="cartera-alert" role="status">Esta vista usa temporalmente el archivo cargado y no modifica la cartera financiera del sistema. Saldo: {data.metadata?.balance_source?.toLowerCase() || "cartera del archivo"}.</div>
    {data.configuration_warnings?.map((warning, index) => <div className="cartera-alert" role="status" key={index}>{warning}</div>)}
    <section className="cartera-summary-grid" aria-label="Resumen del pipeline importado">{[["Clientes procesados", data.summary?.customers], ["Documentos evaluados", data.summary?.documents], ["En mora", data.summary?.overdue], ["Vence hoy", data.summary?.due_today], ["Faltan 5 días", data.summary?.due_in_five_days], ["Pronto pago", data.summary?.prompt_payment], ["Sin etapa", data.summary?.unclassified], ["Errores", data.summary?.errors]].map(([label, count]) => <article key={label} className="cartera-summary-card"><div><span>{label}</span><strong>{count ?? 0}</strong></div></article>)}</section>
    <section className="cartera-panel"><div className="cartera-panel-heading"><div><h2>Clientes en cobranza</h2><p>Etapa y prioridad calculadas por el motor MERTEL.</p></div><span className="cartera-count">{visible.length} de {pipeline.length} clientes</span></div>
      <div className="cartera-filters"><label><span>Buscar nombre, NIT o documento</span><input aria-label="Buscar nombre, NIT o documento" type="search" value={query} onChange={event => setQuery(event.target.value)} /></label><label><span>Etapa</span><select aria-label="Filtrar etapa" value={stage} onChange={event => setStage(event.target.value)}><option value="">Todas</option>{catalog.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}</select></label>
        {[["Cobrador", collector, setCollector, "collector"], ["Vendedor", seller, setSeller, "seller"], ["Ciudad", city, setCity, "city"], ["Zona", zone, setZone, "zone"]].map(([label, value, setter, key]) => <label key={label}><span>{label}</span><select aria-label={`Filtrar ${label.toLowerCase()}`} value={value} onChange={event => setter(event.target.value)}><option value="">Todos</option>{options(key).map(option => <option key={option}>{option}</option>)}</select></label>)}
        <label><span>Ordenar</span><select aria-label="Ordenar clientes" value={sort} onChange={event => setSort(event.target.value)}><option value="priority">Prioridad del motor</option><option value="name">Nombre</option><option value="due">Vencimiento</option><option value="balance">Saldo</option></select></label><button className="cartera-reset" onClick={() => { setQuery(""); setStage(""); setCollector(""); setSeller(""); setCity(""); setZone(""); setSort("priority"); }}>Limpiar filtros</button></div>
      {!pipeline.length ? <div className="cartera-state" role="status"><strong>No hay clientes que puedan ingresar al pipeline con la información disponible en este archivo.</strong></div> : !visible.length ? <div className="cartera-state" role="status"><strong>No hay clientes que coincidan con la búsqueda o los filtros.</strong></div> : <div className="cobranza-client-grid">{visible.map(item => { const invoice = item.main_invoice?.invoice; return <article key={item.customer.id} className="cobranza-client-card"><div className="cobranza-card-heading"><div><h3>{item.customer.name || "No informado"}</h3><span>NIT {item.customer.nit || "—"}</span></div><StageBadge item={item} catalog={catalog} /></div>
        <p className="cobranza-card-balance"><span>Saldo pendiente</span><strong>{amount(item.total_balance)}</strong></p><dl><div><dt>Documento principal</dt><dd>{invoice?.invoice_number || "—"}</dd></div><div><dt>Emisión</dt><dd>{formatDate(invoice?.issue_date)}</dd></div><div><dt>Vencimiento</dt><dd>{formatDate(invoice?.due_date)}</dd></div><div><dt>Situación</dt><dd>{item.main_invoice?.days_until_due < 0 ? `${Math.abs(item.main_invoice.days_until_due)} días de mora` : item.main_invoice?.days_until_due === 0 ? "Vence hoy" : `${item.main_invoice?.days_until_due ?? "—"} días restantes`}</dd></div><div><dt>Cobrador</dt><dd>{item.source_details?.collector || "—"}</dd></div><div><dt>Vendedor</dt><dd>{item.source_details?.seller || "—"}</dd></div></dl><p className="cobranza-note">{item.reason}</p><div className="cobranza-card-actions"><button className="cartera-link-button" onClick={() => setSelected(item)}>Ver cliente y documentos ({item.documents?.length || 0})</button></div></article>; })}</div>}
    </section>
    {data.errors?.length > 0 && <section className="cartera-panel"><button className="cartera-reset" aria-expanded={showErrors} onClick={() => setShowErrors(value => !value)}>{data.errors.length} registros no pudieron procesarse · {showErrors ? "Ocultar" : "Consultar errores"}</button>{showErrors && <ul>{data.errors.map((error, index) => <li key={`${error.source_row}-${error.code}-${index}`}>Fila {error.source_row || "—"} · {error.code}: {error.message}</li>)}</ul>}</section>}
    {selected && <div className="cartera-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) close(); }}><section className="cartera-modal cobranza-modal" role="dialog" aria-modal="true" aria-labelledby="imported-detail-title"><header className="cartera-modal-header"><div><h2 id="imported-detail-title">{selected.customer.name || "Cliente"}</h2><p>Fuente: archivo de cartera MERTEL · Referencia {formatDate(data.source?.reference_date)}</p></div><button className="cartera-close" aria-label="Cerrar detalle" onClick={close}><X size={19} /></button></header><div className="cartera-modal-body"><h3>Datos del cliente</h3><div className="cobranza-detail-grid">{[["NIT", "nit"], ["Representante legal", "representative"], ["Dirección", "address"], ["Ciudad", "city"], ["Departamento", "department"], ["Teléfono", "phone"], ["Celular", "mobile"], ["Cupo", "credit_limit"], ["Cobrador", "collector"], ["Vendedor", "seller"], ["Zona", "zone"]].map(([label, key]) => <DetailValue key={key} label={label}>{selected.source_details?.[key]}</DetailValue>)}</div><h3>Documentos del archivo</h3><div className="cartera-table-wrap"><table className="cartera-table cobranza-table"><thead><tr><th>Documento</th><th>Movimiento</th><th>Emisión</th><th>Vencimiento</th><th>Valor</th><th>IVA</th><th>Saldo de cartera</th><th>Etapa</th><th>Observaciones</th><th>Estado</th></tr></thead><tbody>{selected.documents.map((document, index) => <tr key={`${document.source_row}-${index}`}><td>{document.document_number || "—"}</td><td>{document.movement || "—"}</td><td>{formatDate(document.issue_date)}</td><td>{formatDate(document.due_date)}</td><td>{amount(document.document_value)}</td><td>{amount(document.iva)}</td><td>{amount(document.balance)}</td><td>{document.stage_label || "—"}</td><td>{document.observations || "—"}</td><td>{document.movement_type === "invoice" ? document.eligible ? "Clasificado" : "Sin etapa" : "Informativo; no se aplica a factura"}</td></tr>)}</tbody></table></div><p className="cobranza-note">Pronto Pago puede requerir revisión manual de productos. Este resultado no aplica descuentos ni realiza cambios financieros.</p></div><footer className="cartera-modal-footer"><button className="cartera-button-secondary" onClick={close}>Cerrar</button></footer></section></div>}
  </section>;
}
