CREATE TABLE mertel_customer_resolution_rows (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  company_id BIGINT UNSIGNED NOT NULL,
  import_batch_id BIGINT UNSIGNED NOT NULL,
  identity_key VARCHAR(64) NOT NULL,
  nit_normalized VARCHAR(20) NULL,
  source_rows JSON NOT NULL,
  source_data JSON NOT NULL,
  status ENUM('SEARCHING','FOUND','NEW','AMBIGUOUS','INVALID','PERSISTENT','RESOLVED') NOT NULL DEFAULT 'SEARCHING',
  customer_id BIGINT UNSIGNED NULL,
  differences JSON NULL,
  decision VARCHAR(50) NULL,
  decision_reason VARCHAR(500) NULL,
  updated_by BIGINT UNSIGNED NULL,
  resolved_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_mertel_resolution_batch_identity (import_batch_id, identity_key),
  KEY idx_mertel_resolution_company_status (company_id, status),
  KEY idx_mertel_resolution_nit (company_id, nit_normalized),
  CONSTRAINT fk_mertel_resolution_batch FOREIGN KEY (import_batch_id) REFERENCES import_batches(id) ON DELETE CASCADE,
  CONSTRAINT fk_mertel_resolution_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_mertel_resolution_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_mertel_resolution_user FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
